name: toolbox_tree
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - cheroot
  - conda-forge::gcc_linux-64
  - python=3.13
  - biopython=1.86
  - mafft
  - flask
  - flask-cors
  - sqlalchemy
  - numpy
  - pyqt6
  - dnspython
  - pip
  - pip:
      - email-validator
      - ete4==4.4.0